sandialabs/seacas

ACCESS/libraries/ioss/src/exo_par/Iopx_DatabaseIO.C

Was getting compiler error on Intel/15.0.2 regarding "std::numeric_limits" missing from namespace of std.

Added <limits> include statement.

---

packages/seacas/scripts/blot
packages/seacas/scripts/blot.in
packages/seacas/scripts/fastq
packages/seacas/scripts/fastq.in

When using Fastq interactively, I was mildly annoyed by segfaults printing "Fastq Successful Execution," so I changed the script's behavior to only display that message when these programs exit with code zero. This happens when Fastq is exited with ex and when Blot is exited with exi, qui, or end.
If printing this message on an error is intentional behavior feel free to discard this PR though.

This fixes Blot and Fastq printing Successful Execution when exiting with error

---

packages/seacas/applications/nem_slice/elb.h
packages/seacas/applications/nem_slice/elb_elem.C
packages/seacas/applications/nem_slice/elb_elem.h
packages/seacas/applications/nem_slice/elb_inp.C
packages/seacas/applications/nem_slice/elb_loadbal.C
packages/seacas/applications/nem_slice/elb_main.C
packages/seacas/applications/nem_slice/fix_column_partitions.C
packages/seacas/applications/nem_slice/fix_column_partitions.h

This adds an optional capability to detect vertical columns of elements in meshes and ensure that the elements of any particular column are not assigned to different partitions. The only restriction on the code is that the columns must have strictly vertical sides (lateral face normal must not have a z-component). The top and bottom faces of the elements in a column do not have to be horizontal. The meshes may also have some semi-structured and some unstructured parts. The columnar elements can be hexes or wedges (with degenerate lateral faces).
This option is accessed by -C on the command line or by using "fix_columns" in the "MISC_OPTIONS" in the input file

nem_slice enhancement to detect and manage column in mesh

---

packages/seacas/applications/nem_slice/fix_column_partitions.C

Two minor bugs were preventing the code from deducing columns in prismatic meshes - instead the column was growing indefinitely with repeated elements. Fixed (tested on some large meshes with about a million elements)

Fix an error in column deduction in prismatic meshes

---

packages/seacas/applications/ejoin/EJ_mapping.C

Without <numeric>, breakage was: No itoa in namespace std (Intel compiler; icpc (ICC) 17.0.4 20170411)

Add numeric header (absence broke Intel compile)

---

packages/seacas/libraries/exodus/src/ex_utils.c

The code had been comparing against a pointer to characters rather than
a character.

ex_utils: compare characters against NUL

---

packages/seacas/libraries/exodus/include/exodusII_int.h

Visual Studio 2013 only supports `__func__` in C++ code and `snprintf`
is available as `_snprintf`.

exodus: support older Visual Studio compilers

---

packages/seacas/libraries/ioss/src/Ioss_GroupingEntity.h

There was a use of Kokkos dimension_0() and dimension_1(), which are
deprecated by Kokkos in favor of extent(0) and extent(1).
Built with KOKKOS=ON before and after the change with GCC 4.9.3.

change use of Kokkos dimension_N to extent(N)

---

cmake/tribits/common_tpls/find_modules/FindNetCDF.cmake

Issue #91
Fix a missing string that was used to determine the netcdf_max_vars. The missing
string caused that value to be empty.
Fixed the use of keyword "GREATER_EQUAL" in an if. That keyword didn't exist until
CMake 3.7 and the minimum version required is 3.1.

Fix configuration issue with netcdf < 4.5

---

packages/seacas/libraries/aprepro_lib/apr_aprepro.cc

Issue #120
In certain usages of the Aprepro class the outputStream stack might
have no elements in it so calling flush on the top element segfaults.
The fix is to check that outputStream has > 0 elements.

Aprepro_lib: fix potential segfault in destructor

---

packages/seacas/libraries/exodus_for/CMakeLists.txt

When compiling Exodus Fortran libraries, the following error is thrown:
CMake Error at packages/seacas/libraries/exodus_for/CMakeLists.txt:37 (InstallSymLink):
Unknown CMake command "InstallSymLink".
This minor patch fixes this.

Exodus fortran cmake bug fix

---

packages/seacas/libraries/exodus/include/exodusII_int.h

`PRId64` is now provided by VS2015 and causes warnings about
redefinition if done here.

exodusII_int: use inttypes.h for VS2015 and newer

---

packages/seacas/applications/exodiff/iqsort.C

Otherwise on alpine linux, using gcc 8.3.0, I get
```
[...]/iqsort.C:170:33: error: 'int64_t' does not name a type
template void index_qsort(const int64_t v[], int64_t iv[], size_t N);
^~~~~~~
[...]/iqsort.C:170:46: error: 'int64_t' has not been declared
template void index_qsort(const int64_t v[], int64_t iv[], size_t N);
^~~~~~~
[...]/iqsort.C:170:68: error: duplicate explicit instantiation of 'void index_qsort(const T*, INT*, size_t) [with T = int; INT = int; size_t = long unsigned int]' [-fpermissive]
template void index_qsort(const int64_t v[], int64_t iv[], size_t N);
^
[..]/iqsort.C:171:45: error: 'int64_t' has not been declared
template void index_qsort(const double v[], int64_t iv[], size_t N);
^~~~~~~
[...]/qsort.C:171:67: error: duplicate explicit instantiation of 'void …
```

Include cstdint

---

packages/seacas/applications/explore/CMakeLists.txt

Need to be able to disable the build of the SEACAS 'explore' executable for cuda+rdc builds for now with -Dexpore_EXE_DISABLE=ON (see trilinos/Trilinos#6008).
This matches the PR trilinos/Trilinos#6121 and must be merged here in the seacas github repo or the next snapshot to Triilnos will wipe out these changes.

SEACAS: Allow for disable of explore exe (trilinos/Trilinos#6008)

---

packages/seacas/scripts/exodus3.in.py

fixed a discrepancy with the versioning.
changed the ctype to be explicit,  ` from ctypes import *` to `import ctypes` which is better practice.
could also have only imported the relevant functions, but if enough are used to use `*` then using explicitly makes the most sense I think.

style: replace import * with calling each thing

---

packages/seacas/libraries/exodus/src/ex_create_par.c
packages/seacas/libraries/exodus/src/ex_open_par.c

GCC 10 is now stricter it seems.

exodus: avoid a linker error about duplicate symbols

---

packages/seacas/libraries/exodus/test/CMakeLists.txt

This only sets the test properties if the tests get added and it makes the code much more simple and robust to maintain.  (There was a better way :-) )  See:
* https://tribits.org/doc/TribitsDevelopersGuide.html#setting-additional-test-properties-tribits-add-test
This has to be done or you get a configure error when you configure with the new option [`<Project>_SKIP_CTEST_ADD_TEST=ON`](https://tribits.org/doc/TribitsBuildReference.html#disabling-just-the-ctest-tests-but-not-the-test-executables). (See TriBITSPub/TriBITS#317 and [ATDV-183](https://sems-atlassian-srn.sandia.gov/browse/ATDV-183).)
This patch is also applied in the Trilinos PR:
* https://github.com/trilinos/Trilinos/pull/7325
in the commit:
* https://github.com/trilinos/Trilinos/pull/7325/commits/8090c235a2e665e14222729d1ac3a3 …

SEACAS: Set test dependencies using result of ADDED_TEST_NAMES_OUT args (ATDV-183)

---

packages/seacas/IossProperties.md
packages/seacas/libraries/ioss/src/Ioss_Decomposition.C
packages/seacas/libraries/ioss/src/Ioss_Decomposition.h

@gdsjaar 
This is a matching PR for https://github.com/trilinos/Trilinos/pull/7812
This PR adds the option of using common_nodes=2, which will be used when constructing the dual graph in ParMETIS_V3_PartMeshKway. When common_nodes=2, elements which share a common edge are connected in the dual graph. This will increase the number of connections in the dual graph (unless the elements are triangular), so captures the total communication volume more correctly in the case of an edge-based discretization.
I obtained up to 10% improvement in the solve time when I used common_nodes=2 on a tetrahedral mesh.

IOSS: Add environment variable to set common_nodes to 2

---

packages/seacas/libraries/ioss/src/main/glob.h

this is needed in order to call delete
on SetItem base class pointers, which
SEACAS does.

Add virtual destructor to SetItem

---

packages/seacas/libraries/aprepro_lib/apr_aprepro.cc
packages/seacas/libraries/aprepro_lib/apr_util.cc
packages/seacas/libraries/aprepro_lib/aprepro.h

Pull over Sierra/SD generated PR to the seacas github repository.

APREPRO: Add --require_defined flag to treat undefined var as error

---

packages/seacas/libraries/exodus/src/ex_utils.c

this prevents out of bounds access when the fifth
character is set to the null character for later
printing: the array needs to be five characters
long.

Increase size of magic array for null character

---

packages/seacas/applications/exodiff/CMakeLists.txt
packages/seacas/applications/exodiff/ED_SystemInterface.C
packages/seacas/applications/exodiff/ED_SystemInterface.h
packages/seacas/applications/exodiff/MinMaxData.h
packages/seacas/applications/exodiff/create_file.C
packages/seacas/applications/exodiff/edge_block.C
packages/seacas/applications/exodiff/edge_block.h
packages/seacas/applications/exodiff/exoII_read.C
packages/seacas/applications/exodiff/exoII_read.h
packages/seacas/applications/exodiff/exo_entity.C
packages/seacas/applications/exodiff/exodiff.C
packages/seacas/applications/exodiff/face_block.C
packages/seacas/applications/exodiff/face_block.h
packages/seacas/applications/exodiff/test_generate_exo_files.c

This PR adds edge/face variable comparison to exodiff.  The features are tested using a new test file generator that creates 4 exodus files.  The `exodiff_test_edge_face` ctest compares a base (gold) exodus file to exodus files with no diffs, edge diffs and face diffs.
Closes #201

EXODIFF: add Edge Block and Face Block capabilities to exodiff

---

packages/seacas/libraries/exodus/src/ex_get_name.c

Use the ex_get_assembly function to get the name of assemblies
in ex_get_name for consitency across the data structures.

EXODUS: ex_get_name now works with assemblies.

---

cmake/tribits/common_tpls/find_modules/FindHDF5.cmake
packages/seacas/libraries/ioss/src/Ioss_FaceGenerator.C
packages/seacas/libraries/ioss/src/Ioss_ParallelUtils.h
packages/seacas/libraries/ioss/src/Ioss_Utils.C
packages/seacas/libraries/ioss/src/exodus/Ioex_ParallelDatabaseIO.C

HDF5 calls their targets something based on both static/shared and component, so this makes it easier to find them by just letting HDF5 tell us what they are. This fixes the build for me when using all static libraries, because HDF5 is better able to include things like `zlib` in its exported targets.

Fixes for static libraries and Windows

---

packages/seacas/libraries/exodus/src/ex_get_assemblies.c
packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

Allow for the ex_get_assemblies function to be called from
the exodus python interface. Includes a unittest as well.
Updated some Copyrights.

exodus.py: Provide exodus.py with the get_assemblies function

---

packages/seacas/scripts/decomp
packages/seacas/scripts/decomp.in

Adds a `--spread-suffix|-X` option to `decomp` to specify the file suffix for files created by `decomp` (`nem_spread`).
Why?  This change will allow ALEGRA to update from our old tools to `decomp` with minimal pain (ALEGRA proper and hundreds of tests assume that the parallel files have `.par.M.N` extensions).

Allow changing parallel file extension by files emitted by decomp

---

packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

The assembly type was allowing non-integer values for type
to be passed in and stored. Now the stored values should be
int types while strings or entity_type enums can be passed
and converted to integers. This should keep the interface
working from assembly to ex_assembly as before but more strictly
align with the documentation for what the type of "type" is in
an assembly object.

assembly: make the assembly types line up with ex_assemblies

---

packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

Add support for the get_reduction_variable_name method
and ensure it works with assemblies.
Add tests to enforce the types ("EX_ASSEMBLY" or ex_entity_type.EX_ASSEMBLY)
are both useable.

exodus3.py: Add support for get_reduction_variable_name

---

packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C

MSVC 2015 doesn't compile when capturing stack-allocated arrays by
value in a lambda expression.

Capture arrays by reference rather than value

---

packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C

seems necessary for some msvc version

Ioss: Missing strncasecmp define

---

packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

Clean up some spacing and remove semi-colons.
Fix a small memory leak in _getExodusVersion().
Add some tests for exodus3.py.

EXODUS.py Cleaning and Testing

---

packages/seacas/libraries/ioss/src/Ioss_Compare.C

Workaround gcc 4.8.5's lack of support for const iterators
as arguments to std::vector::erase().

gcc 4.8.5: use non-const iterators for std::vector::erase()

---

packages/seacas/libraries/ioss/src/faodel/Iofaodel_Utils.C
packages/seacas/libraries/ioss/src/faodel/Iofaodel_Utils.h

The Iofaodel::get_entity_names() signature in the .C was updated in 443760c5627105d689fd88fe4bfb5f5897758562, but the .h was not.  This PR brings them into sync.

IOSS: fix Iofaodel::get_entity_names() signature mismatch between .h and .C

---

cmake/RepositoryDependenciesSetup.cmake
packages/seacas/CMakeLists.txt
packages/seacas/cmake/SeacasDisableSubpackagesDependingOnFortran.cmake

@gsjaardema 
This is an identical PR to the Trilinos PR trilinos/Trilinos#9772 to address trilinos/Trilinos#3346.
This makes sure future snapshots of SEACAS into Trilinos will not overwrite the changes in PR trilinos/Trilinos#9772
To test this, believe it or not, I used the same [SEMS Dev Env](https://github.com/trilinos/Trilinos/wiki/SEMS-Dev-Env) and loaded the env with:
```
$ source ~/Trilinos/cmake/load_sems_dev_env.sh
$ module list
Currently Loaded Modulefiles:
1) sems-env                                     6) sems-gcc/7.2.0                              11) sems-netcdf/4.7.3/parallel
2) sems-python/2.7.9                            7) sems-openmpi/1.10.1                         12) sems-parmetis/4.0.3/parallel
3) sems-cmake/3.17.1                            8) sems-boost/1.63.0/base …
```

SEACAS: Move logic to disable SEACAS subpackages that depend on Fortran (trilinos/Trilinos#3346)

---

packages/seacas/scripts/CMakeLists.txt

Make sure exodus.py tests work without the ACCESS and INSTALL_PATH
environment variables set at install time.

EXODUS.PY: Make sure it works when installed with environment variables.

---

packages/seacas/libraries/ioss/src/Ioss_Utils.C

`.rbegin()` cannot be used on empty strings, so check for it.
---
I used `empty() ||` rather than `!empty() &&` because it does not have a trailing digit.

Ioss_Utils: guard against empty strings

---

packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h

`cctype` includes `ctype.h`, so `ctype.h` is no longer included here.

IOSS: include cctype to define ::toupper and std::isdigit

---

packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h

Fixes MSVC2017 compile error where `std::isspace` and `std::isdigit`
are not defined.

Include cctype instead of ctype.h

---

packages/seacas/libraries/aprepro_lib/apr_aprepro.cc

This will make it more clear that passing --debug will keep around
the temporary files used for arrays by aprepro.

APREPRO: Add detail to the --debug help message

---

packages/seacas/libraries/ioss/src/Ioss_Utils.C
packages/seacas/libraries/ioss/src/Ioss_Utils.h

Making certain functions in Ioss::Utils non-inline to avoid export
errors on Windows. Accessing the non-exported static variables was
causing errors. This avoids that. Also added API to access current
values for various streams.

Windows fixes: make functions non-inline

---

packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

This adds functionality to add being able to easily find the
elements contained within EX_ELEM_BLOCK or other type without
keeping track of global and internal indicies.

EXODUS.PY: Add the get_block_id_map method

---

packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

This will allow the use of with statements for opening and closing
exodus files, including methods which return exodus class objects,
such as exodus.copy.

EXODUS.PY: Add context manager functionality to the exodus class

---

packages/seacas/scripts/exodus3.in.py

Exodus objects can now be used through with statements.
This change makes the documented usages reflect this change
so it can be easily found.

EXODUS.PY: Update documentation to reflect contextmanager changes

---

packages/seacas/libraries/ioss/src/Ioss_VariableType.C

The state of `ignore_realn_fields` is not considered when handing out a variable from the factory registry. Fix #314

Avoid Real[N] in registry if ignoring such fields

---

packages/seacas/libraries/exoIIv2for32/src/exo_jack_32.c
packages/seacas/libraries/exodus_for/src/addrwrap.F
packages/seacas/libraries/exodus_for/src/exo_jack.c
packages/seacas/libraries/exodus_for/test/testpart.f90

This is not ready for inclusion. @gsjaardema can you help me figure out why the wrapper expo does not show up in `libexoIIv2for.a`?

Adding fortran wrapper for ex_put_partial_var

---

packages/seacas/scripts/exodus3.in.py

A couple modifications to make an easier workflow for:
- Create an empty exodus file
- Add some qa / info records to the created file
- Copy an existing file onto the end of the created file
With the current api, it does not seem possible to create an empty file (with mode 'w' or 'w+') since there is an assertion that the `info` does not contain any None items.
This refactor removes that assertion and only outputs the initial parameters (ex_put_init call) if there is valid data.
It also exposes the `copy_file` function which takes the `file_id` of an already opened file instead of a filename.
This makes it posssible to append qa records to a file using:
```
original = exodus.exodus(ORIG_PATH)
qa_recs = original.get_qa_records()
with exodus.exodus(COPY_PATH, mode='w+') as exofile:
QA = …
```

EXODUS.PY: Proposed refactor in create/copy api to make things easier

---

packages/seacas/libraries/ioss/src/Ioss_Region.C

The recent patch for negative time support worked well, but it segfaults when the dataset does not have times.

Fix out of bounds error in get_max_time

---

packages/seacas/scripts/tests/test_exodus3.py

The interface for copy_file was exposed as part of merge request #325. This adds a test for it to the unittests.

EXODUS.PY: Add a test for the copy_file method

---

packages/seacas/libraries/ioss/src/pamgen/Iopg_DatabaseIO.h

GCC 10 would fail to compile pamgen due to a pure virtual method not being overridden. This adds the missing override.

Iopg_DatabaseIO.h: Add missing Assemlby get_field_internal macro

---

packages/seacas/libraries/ioss/src/Ioss_FileInfo.C

Build fails on musl-based Linux distributions.
As for glibc, `sys/unistd.h` contains `#include <unistd.h>`, thus pointing to `unistd.h`.
Reference: void-linux/void-packages#40423 (https://github.com/void-linux/void-packages/actions/runs/3432806790/jobs/5722449115):
```
/builddir/vtk-9.2.2/ThirdParty/ioss/vtkioss/Ioss_FileInfo.C:29:10: fatal error: sys/unistd.h: No such file or directory
29 | #include <sys/unistd.h>
|          ^~~~~~~~~~~~~~
compilation terminated.
[8820/10163] Building CXX object ThirdParty/ioss/vtkioss/CMakeFiles/ioss.dir/Ioss_FieldManager.C.o
ninja: build stopped: subcommand failed.
=> ERROR: vtk-9.2.2_1: do_build: '${make_cmd} ${makejobs} ${make_build_args} ${make_build_target}' exited with 1
=> ERROR:   in do_build() at common/build-style/cmake.sh:93
Error: Process …
```

Ioss_FileInfo.C: use unistd.h instead of sys/unistd.h

---

packages/seacas/scripts/tests/test_exodus3.py

Change strings to use Python 3 formating and clean up identity comprehensions.
Also moves a variable instanciation outside of a loop.

TEST_EXODUS3.PY: Refactor tests

---

packages/seacas/libraries/ioss/src/visualization/catalyst/ioss2catalyst/IossApplication.cxx
packages/seacas/libraries/ioss/src/visualization/catalyst/ioss2catalyst/IossApplication.h
packages/seacas/libraries/ioss/src/visualization/exodus/Iovs_exodus_DatabaseIO.C
packages/seacas/libraries/ioss/src/visualization/exodus/Iovs_exodus_DatabaseIO.h

Provide implementations for all put_field_internal methods for unsupported IOSS entity types. These
implementations return num_to_get.
Fix return types in ioss2catalyst test code.

Catalyst Exodus Database

---

.github/workflows/python-linting.yml
install-tpl.sh
packages/seacas/scripts/exodus3.in.py

Fix the `__ex_get_one_attr` function to correctly query the number of entities (nodes, elements) in the set or block.  Still not as generic as it should be and we should probably refactor into a separate function the code returning `numVals` as it is used in at least two places in the code.  
@mvlopri

EXODUS.PY: Fix element attribute query by name

---

packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

Some minor refactors were done to the exodus3.py script and tests were written for put_elem_attr, get_elem_attr, and get_entity_count.

EXODUS.PY: Refactor and add tests

---

cmake/tribits/common_tpls/FindTPLHDF5.cmake

HDF5 exports a version compatibility
file that requires that the major
*and minor* version numbers agree
to be compatible.
Thus, if we give version 1.10 to
find_package, it will not accept
HDF5 1.13 for example.
Since the "modern" mode is opt-in,
it may be easiest just to remove
this minimum version since it was
just a guess anyways.
@bartlettroscoe

remove modern HDF5 version check

---

CMakeLists.txt

This allows the use of the full SEACAS package to be included as a cmake_add_subdirectory from a CMake project above it.

Bugfix for CMakeLists.txt

---

packages/seacas/libraries/ioss/src/Ioss_Property.C
packages/seacas/libraries/ioss/src/Ioss_Property.h
packages/seacas/libraries/ioss/src/Ioss_PropertyManager.C

Replace the union in Ioss::Property with a std::variant.

IOSS: Make Ioss_Property.h use variant instead of union

---

packages/seacas/libraries/ioss/src/Ioss_FileInfo.C

The sys/statfs.h header is a linux thing, but it was being included for all non-Window/Mac. This broke building on FreeBSD, and probably other OSes too.
After consulting various man pages from various OSes, we now include the right headers per-OS for the statfs() function.

Fixed build errors related to sys/statfs.h include

---

packages/seacas/libraries/ioss/src/Ioss_FileInfo.C

#include <sys/statfs.h> not only for linux, but as a general fallback.
Thanks to Adrien Stucky for finding the problem.

Fixed reported regression building with Emscripten

---

cmake/tribits/common_tpls/FindTPLCGNS.cmake

CGNS now contains a cgns-config.cmake file.
Here, we are updating FindTPLCGNS.cmake to be able to find that.

Update find of CGNS using modern cmake files.

---

packages/seacas/libraries/ioss/src/Ioss_DatabaseIO.C
packages/seacas/libraries/ioss/src/Ioss_Utils.h
packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
packages/seacas/libraries/ioss/src/text_mesh/Iotm_DatabaseIO.C
packages/seacas/libraries/ioss/src/text_mesh/Iotm_DatabaseIO.h
packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.C
packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.h
packages/seacas/libraries/ioss/src/unit_tests/CMakeLists.txt
packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmDatabaseIO.C

The text mesh database did not support omitted element blocks and assemblies . This is a fix to enable that oversight

TextMesh: Enable block and assembly omission/inclusion

---

packages/seacas/libraries/ioss/src/text_mesh/Iotm_DatabaseIO.C
packages/seacas/libraries/ioss/src/text_mesh/Iotm_DatabaseIO.h
packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.C
packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.h
packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmDatabaseIO.C

Propagated consistent EntityId (int64_t) through code
Added unit tests for various forms of sideset/sideblock creation

TextMesh: Enable block membership capability for sidesets and sideblocks

---

packages/seacas/applications/ejoin/EJoin.C
packages/seacas/libraries/ioss/src/Ioss_Transform.C
packages/seacas/libraries/ioss/src/Ioss_Transform.h
packages/seacas/libraries/ioss/src/Ioss_TransformFactory.C
packages/seacas/libraries/ioss/src/Ioss_TransformFactory.h
packages/seacas/libraries/ioss/src/main/io_shell_ts.C
packages/seacas/libraries/ioss/src/transform/Iotr_MinMax.C
packages/seacas/libraries/ioss/src/transform/Iotr_MinMax.h
packages/seacas/libraries/ioss/src/transform/Iotr_Offset.C
packages/seacas/libraries/ioss/src/transform/Iotr_Offset.h
packages/seacas/libraries/ioss/src/transform/Iotr_Offset3D.C
packages/seacas/libraries/ioss/src/transform/Iotr_Offset3D.h
packages/seacas/libraries/ioss/src/transform/Iotr_Scale.C
packages/seacas/libraries/ioss/src/transform/Iotr_Scale.h
packages/seacas/libraries/ioss/src/transform/Iotr_Scale3D.C
packages/seacas/libraries/ioss/src/transform/Iotr_Scale3D.h
packages/seacas/libraries/ioss/src/transform/Iotr_Tensor.C
packages/seacas/libraries/ioss/src/transform/Iotr_Tensor.h
packages/seacas/libraries/ioss/src/transform/Iotr_VectorMagnitude.C
packages/seacas/libraries/ioss/src/transform/Iotr_VectorMagnitude.h

Move the Iotr::Factory to Ioss::TransformFactory to make it easier/clearer for clients on how to create and work with transforms.  No longer need to be concerned with the transform/ subdirectory.

IOSS: Move transform factory from Iotr to Ioss

---

packages/seacas/cmake/FortranSettings.cmake
packages/seacas/libraries/exodus_for/src/addrwrap.F
packages/seacas/libraries/exodus_for/src/exo_jack.c

The flang-new compiler did not have the gnu fortran extensions of MALLOC and FREE. Rewrote addrwrap.F and exo_jack.c to not require the fortran malloc/free -- now any integer conversions are done in exo_jack.c.
Need to see if can reduce code duplication in exo_jack.c, but addrwrap.F is much cleaner...

EXODUS_FOR: Refactor to avoid fortran malloc free

---

packages/seacas/libraries/ioss/src/Ioss_MemoryUtils.C

Hi @gsjaardema! 👋🏻 
I ran across an error building SEACAS / IOSS on Intel Mac (the Mac SDK was missing `mach/arm/kern_return.h`) that I hadn't on my Apple Silicon system. Guarding against using that include on Intel Mac platforms seemed to be the right fix, so I wanted to contribute it back to you. 
EDIT: Double-checking with INL the terms of the CLA. Thanks for your patience!

IOSS: Add guard for ARM/ARM64-specific include on Mac

---

packages/seacas/libraries/ioss/src/catalyst/Iocatalyst_DatabaseIO.C
packages/seacas/libraries/ioss/src/catalyst_tests/Iocatalyst_BlockMeshSet.C
packages/seacas/libraries/ioss/src/catalyst_tests/Iocatalyst_DatabaseIOTest.h
packages/seacas/libraries/ioss/src/catalyst_tests/Iocatalyst_ElementBlockTest.C

A sequel to the work done in #456 
Added it such that the changes made in our Catalyst Database from the Exodus Properties (on read) are also reflected/copied into the conduit representation, such that getting the field data (which accesses conduit) works as expected.

Catalyst: Add support for Exodus IOSS Properties in Conduit Representation

---

packages/seacas/Jamfile

Jamfile change for Sierra's build system to support a spack built version of Seacas. 
This change correctly matches Seacas library names to CMake's version of Seacas's libraries and changes the path name to 'seacas' rather than 'sierra_seacas'

Correct Jamfile to match Seacas's CMake Library Names

---

packages/seacas/libraries/ioss/src/catalyst/Iocatalyst_DatabaseIO.C
packages/seacas/libraries/ioss/src/catalyst_tests/CMakeLists.txt
packages/seacas/libraries/ioss/src/catalyst_tests/Iocatalyst_ConduitReadTest.C
packages/seacas/libraries/ioss/src/catalyst_tests/Iocatalyst_DatabaseIOTest.C
packages/seacas/libraries/ioss/src/catalyst_tests/Iocatalyst_DatabaseIOTest.h

Fixed crash bug when IOSS field suffix separator is empty.
Added tests for case when reading from Conduit files written by Catalyst IOSS database.
Changed time step selection when reading from Conduit files to use the IOSS integer property CATALYST_READER_TIME_STEP instead of IOSS database filename.

Catalyst API 2

---

packages/seacas/libraries/ioss/src/catalyst/Iocatalyst_DatabaseIO.C
packages/seacas/libraries/ioss/src/catalyst_tests/Iocatalyst_ConduitReadTest.C

Allow CATALYST_READER_TIME_STEP to be defined as an environment variable.
Changed default timestep to 0 for reading from Conduit files.

IOSS: Catalyst API 2

---

packages/seacas/libraries/ioss/src/Ioss_DatabaseIO.C
packages/seacas/libraries/ioss/src/Ioss_DatabaseIO.h
packages/seacas/libraries/ioss/src/Ioss_DynamicTopology.C
packages/seacas/libraries/ioss/src/Ioss_DynamicTopology.h
packages/seacas/libraries/ioss/src/Ioss_IOFactory.C
packages/seacas/libraries/ioss/src/Ioss_Region.C
packages/seacas/libraries/ioss/src/Ioss_Region.h
packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.h
packages/seacas/libraries/ioss/src/exodus/Ioex_Utils.C
packages/seacas/libraries/ioss/src/unit_tests/CMakeLists.txt
packages/seacas/libraries/ioss/src/unit_tests/UnitTestDynamicTopology.C
packages/seacas/libraries/ioss/src/utest/Ut_ioad.C

Reverts sandialabs/seacas#471.  Original PR is #469 
This should get back to the original Dynamic Topology PR merge by Tolu.  The issues that it triggered turned out to be minor and should now be fixed.

Revert "Revert "Dynamic topology region file opening with group I/O""

---

packages/seacas/libraries/ioss/src/Ioss_Decomposition.C
packages/seacas/libraries/ioss/src/Ioss_ParallelUtils.h

`fmt` v11 ([release notes](https://github.com/fmtlib/fmt/releases/tag/11.0.0)) "moved range and iterator overloads of fmt::join to fmt/ranges.h, next to other overloads."
This means the `fmt::join` in `Ioss_Decompoition.C` is not found: https://github.com/sandialabs/seacas/blob/049a054ee0e1c1107336d5996136314f57ddbe2a/packages/seacas/libraries/ioss/src/Ioss_Decomposition.C#L87
This PR adds the necessary `fmt/ranges.h` includes in that and one other place (behind a DEBUG define).
A possible other location that needs adapting (but I was unable to verify) is https://github.com/sandialabs/seacas/blob/049a054ee0e1c1107336d5996136314f57ddbe2a/packages/seacas/libraries/aprepro_lib/aprepro.ll#L154
This change should not have negative effects for older versions of `fmt`.

fix: include fmt/ranges.h in Ioss_Decomposition.C, Ioss_ParallelUtils.h (fmt-11)

---

packages/seacas/Jamfile

Io_system has been moved in the SIERRA source code
This has caused issues with installs due to the need for IOSS headers to be installed in io_system.

io_system Jamfile Changes

---

packages/seacas/libraries/ioss/src/Ioss_Utils.C
packages/seacas/libraries/ioss/src/Ioss_Utils.h
packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.C
packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshAdjacencyGraph.h
packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshTopologyMapping.h

This is a request from STK to extend the ordinal indexing for shells in order to enable referencing the edges

IOSS: Update TextMesh to handle extended shell ordinals to the edges

---

packages/seacas/scripts/exodus3.in.py
packages/seacas/scripts/tests/test_exodus3.py

This was needed to initialize a new exodus file from inside of exodus.py using the init_params argument of the exodus class.
Add a test to ensure this capability does not regress and that ex_init_params works if new arguments need to be initalized in the future.
Address the tests not running due to the test and exodus.py script being placed in lib64. This still needs work to ensure it finds the libexodus.so library because SEACAS_LIBDIR is left blank during the CMake configure step.

Add numBlob to the parameters for the ex_init_params method.

---

packages/seacas/libraries/ioss/src/Ioss_DynamicTopologyObserver.C
packages/seacas/libraries/ioss/src/Ioss_DynamicTopologyObserver.h
packages/seacas/libraries/ioss/src/Ioss_Region.C
packages/seacas/libraries/ioss/src/Ioss_Region.h

Update to allow app the opportunity to clean up any data associated with a Region to prevent memory leaks
This happens when the Region is reset on a topology change

DTIO: Fix app-side memory leak

---

packages/seacas/libraries/ioss/src/Ioss_Region.C

Make sure the correct value of stateCount is returned in the case of a dynamic topology change

DTIO update

---

CMakeLists.txt
cmake/TPLs/FindTPLMatio.cmake

Some of the Trilinos CI builds set `<PACKAGENAME>_ROOT` in the environment, which triggers a CMake policy warning since the version of CMake is set at 3.22.  Use the new behavior explicitly until the minimum version is updated to >= 3.27, which silences the warning (and changes the behavior).
Also removes some (now) redundant policy settings.  I put a comment above the new one to help inform when it's safe to remove.

Fix configure warning in Trilinos

---

TPL/cgns/CGNS-ZLIB.patch
install-tpl.sh

- Patches CGNS to call `find_package(ZLIB)`
- Fixes error shown building static libraries as reported in https://github.com/sandialabs/seacas/issues/631

patches CGNS to use find_package(ZLIB)

---

packages/seacas/applications/algebra/ag_eval.f
packages/seacas/applications/algebra/ag_myamod.f
packages/seacas/applications/algebra/ag_mymax.f
packages/seacas/applications/algebra/ag_mymin.f
packages/seacas/applications/algebra/ag_mysign.f
packages/seacas/applications/algebra/ag_mysum.f
packages/seacas/applications/algebra/ag_qainfo.blk
packages/seacas/libraries/ioss/src/main/shell_interface.C

Recent versions of gfotran are giving type errors for the functions in `eval`.  Everything looks correct and the functions are typed to return REAL, but still get error on a couple functions (not sure why just those few).
This renames all functions that used to start with `MY` with `FUNC` which is by default a real function instead of the implicitly type `M` being integer (even though all are explicitly typed as real).

ALGEBRA: See if this fixes type error

---

packages/seacas/scripts/exomerge3.py
packages/seacas/scripts/tests/exomerge_unit_test.py

In this PR I am proposing an alternative implementation of [_sort_field_names](https://github.com/Damian-AI/seacas/blob/e28323eb37d0380b2197e934dc2d5bc6f7f1b026/packages/seacas/scripts/exomerge3.py#L6914) that fixes #678. The new implementation uses the default Python list sort method with a customized key.
Notes for the reviewer:
- ``exomerge_unit_test.py`` is setup to test only the public API. Since [_sort_field_names](https://github.com/Damian-AI/seacas/blob/e28323eb37d0380b2197e934dc2d5bc6f7f1b026/packages/seacas/scripts/exomerge3.py#L6914) is a private function, I am not sure how to include the test. For the time being, I wrote the test function [_test_sort_field_names](https://github.com/Damian-AI/seacas/blob/e28323eb37d0380b2197e934dc2d5bc6f7f1b026/packages/seacas/scripts/tests/exom …

New implementation of ``_sort_field_names`` based on Python list sorting

---

packages/seacas/scripts/exomerge3.py
packages/seacas/scripts/tests/exomerge_unit_test.py

Add support for field names with two "integration_point" suffices:
```
field_dsa_29_2
```
Support recognizing the IOSS quaternion suffix convention:
```
field_x, field_y, field_z, field_q
fld_s, fld_q
```

Modifications to exomerge field name sorting

---

packages/seacas/libraries/exodus_for/src/exo_jack-windows.c
packages/seacas/libraries/exodus_for/src/exo_jack.c

Mapvar seems to trigger IEEE_DENORMAL with the RELEASE build type because an unused float is uninitialized but used in the EXINQ routine.
This happens on line 282 in mapvar.f
Here is the small test case I was using:
[mapvar_test.tar.gz](https://github.com/user-attachments/files/21124212/mapvar_test.tar.gz)
It is also fixed if you initialize it before the wrapper call if you would rather do it there.
This was with GCC15 with or without mpi.

F2C(EXINQ) initialize float return to avoid IEEE_DENORMAL in mapvar

---

packages/seacas/scripts/exodus3.in.py

Exodus.py will now attempt to look for the lib64 path of SEACAS_LIBDIR if it does not find libexodus.so in the SEACAS_LIBDIR.

Fix for dealing with the possibility that libexodus.so is in lib64
