sandialabs/seacas

TPL/netcdf/runcmake.sh, install-tpl.sh
I don't expect this one to work out of the box, so don't feel obligated to accept it. This PR is to make sure I'm on the right track more than anything.
I've thrown in some checks to avoid recompiling and some error checking to stop the script after a failed compile. I've also included a few more tweaks to make it easier to compile static libraries.
=> Major surgery on install-tpl.sh and some runcmake.sh changes for netcdf.

packages/seacas/libraries/ioss/src/CMakeLists.txt, packages/seacas/libraries/ioss/src/Ioss_Getline.c, packages/seacas/libraries/ioss/src/visualization/Iovs_DatabaseIO.C
I missed some elements in the previous PR
=> Fix Ioss MinGW build

cmake-config
I don't use a bourne style shell so this was breaking the script for me
=> remove space at start of shebang

packages/seacas/libraries/ioss/src/Ioss_FaceGenerator.C, packages/seacas/libraries/ioss/src/Ioss_Utils.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C, packages/seacas/libraries/ioss/src/cgns/Iocgns_Utils.C
=> ioss: fix narrowing warnings

packages/seacas/libraries/ioss/src/cgns/Iocgns_DatabaseIO.C
Remove an accidentally duplicated line.  (Replacing #259 while waiting for approval on CLA signing)
=> Remove duplicate line

packages/seacas/libraries/ioss/src/text_mesh/Iotm_DatabaseIO.C, packages/seacas/libraries/ioss/src/text_mesh/Iotm_DatabaseIO.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.C, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMesh.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h, packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmTextMeshFixture.h, packages/seacas/libraries/ioss/src/unit_tests/UnitTestTextMesh.C
New syntax addition is
"|assembly:[name=;] type=<assembly|block|sideset|nodeset>; [member=member_1,...,member_n]"
=> TextMesh: Add assembly syntax

packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C
Also added a small format change
=> Assembly: Fix logic error when omitting members

cmake/TPLs/FindTPLPthread.cmake
@gsjaardema 
This fixes the file for the new TriBITS implementation snaphshotted into trilinos/Trilinos#10614.  This matches the same file in that  Trilinos PR.
=> Fix FindTPLPthread.cmake for new TriBITS

packages/seacas/scripts/exodus3.in.py
These changes are intended to make exodus.py a bit more pythonic with a few common patterns.
Using newer sytax for formating strings
Using list comprehensions in place of list building for loops Not creating variables just to return them
Preventing latent bugs in mutable default arguments Prenting memory leaks through use of with instead of open Various other refactors
=> EXODUS.PY: Refactor various code patterns

packages/seacas/applications/nem_slice/elb_inp.C
Working toward resolution of #357
=> See what happens to compile subopt on windows

packages/seacas/libraries/ioss/src/Ioss_Map.C
=> IOSS: Fix for valgrind warning

packages/seacas/applications/slice/Slice.C, packages/seacas/libraries/chaco/bpmatch/movevtxs.c, packages/seacas/libraries/ioss/src/Ioss_Field.C, packages/seacas/libraries/ioss/src/Ioss_Field.h, packages/seacas/libraries/ioss/src/Ioss_GroupingEntity.C, packages/seacas/libraries/ioss/src/Ioss_GroupingEntity.h, packages/seacas/libraries/ioss/src/exodus/Ioex_Utils.C, packages/seacas/libraries/ioss/src/visualization/catalyst/phactori/PhactoriDriver.py
Prototype implementation to support the zero-copy API discussed in #282 
@tjotaha @mathstuf @utkarshayachit
=> Ioss zero copy

packages/seacas/scripts/exomerge2.py, packages/seacas/scripts/exomerge3.py
- Fix filename to textwrap to next line
issue https://github.com/sandialabs/seacas/issues/383
=> EXOMERGE: Fix filename textwrap

packages/seacas/libraries/ioss/src/main/io_info.C, packages/seacas/libraries/ioss/src/main/io_modify.C
Modify the io_modify code so that the geometry modification (scale, offset, rotate) commands work for structured cgns meshes.
=> Io modify handle cgns

packages/seacas/applications/nem_slice/elb.h, packages/seacas/applications/nem_slice/elb_elem.C, packages/seacas/applications/nem_slice/elb_loadbal.C, packages/seacas/libraries/ioss/src/Ioss_Region.C
Modifications to support 1D bar/truss models.
=> Decomp support one d

packages/seacas/libraries/ioss/src/Ioss_DatabaseIO.h, packages/seacas/libraries/ioss/src/Ioss_DynamicTopology.C, packages/seacas/libraries/ioss/src/Ioss_DynamicTopology.h, packages/seacas/libraries/ioss/src/Ioss_Region.C, packages/seacas/libraries/ioss/src/Ioss_Region.h, packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.C, packages/seacas/libraries/ioss/src/exodus/Ioex_BaseDatabaseIO.h, packages/seacas/libraries/ioss/src/exodus/Ioex_DatabaseIO.C, packages/seacas/libraries/ioss/src/init/Ionit_Initializer.C, packages/seacas/libraries/ioss/src/unit_tests/UnitTestDynamicTopology.C
IOSS: Add broker class to dynamic topology
The original philosophy of one observer per region is still maintained
with the observers that represent the same FEM model being grouped
together. This means that topology changes on one observer is
propagated to others in the same group
=> Dynamic topology phase 2

packages/seacas/libraries/aprepro_lib/strings.cc, packages/seacas/libraries/ioss/src/exodus/Ioex_Utils.C, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshAdjacencyGraph.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshAssembly.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshDataTypes.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshEntityGroup.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshNodeset.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshSideset.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshSidesetSkinner.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshSidesetSplitter.h, packages/seacas/libraries/ioss/src/text_mesh/Iotm_TextMeshUtils.h, packages/seacas/libraries/ioss/src/unit_tests/UnitTestIotmTextMeshFixture.h, packages/zoltan/siMPI/pyMPI/siMPI/fortran_grinder.c, packages/zoltan/siMPI/pyMPI/siMPI/fortran_parameterize.c, packages/zoltan/src/driver/dr_loadbal.c, packages/zoltan/src/driver/dr_loadbalCPP.cpp, packages/zoltan/src/driver/dr_param_file.c
Fix usages of strcasecmp/strncasecmp
=> Fix usages of strcasecmp/strncasecmp

packages/seacas/libraries/aprepro_lib/strings.cc, packages/seacas/libraries/exodus/src/ex_field_utils.c
Remove restrict usage.
This caused compilation issues on our end.
=> Remove restrict usage

packages/seacas/applications/grepos/gp_centroid.f, packages/seacas/applications/grepos/gp_comand.F, packages/seacas/applications/grepos/gp_dbmirr.f, packages/seacas/applications/grepos/gp_donrm3.f, packages/seacas/applications/grepos/grepos.f, packages/seacas/libraries/ioss/src/Ioss_Decomposition.C, packages/seacas/libraries/ioss/src/Ioss_Decomposition.h, packages/seacas/libraries/ioss/src/Ioss_Doxygen.h, packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.C, packages/seacas/libraries/ioss/src/exodus/Ioex_DecompositionData.h, packages/seacas/libraries/ioss/src/main/io_shell.C, packages/seacas/libraries/ioss/src/main/shell_interface.C, packages/seacas/libraries/ioss/src/main/shell_interface.h
Start of implementation to have auto-decomp work with omitted blocks.
=> Ioss decomp omitted blocks

README.md, install-tpl.sh
resolves https://github.com/sandialabs/seacas/issues/654
=> switches from wget to curl
